# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Mistral"
license = "MIT"
licenselink = "https://github.com/josephsv96/hugo-theme-mistral/blob/master/LICENSE"
description = ""
homepage = "https://github.com/josephsv96/hugo-theme-mistral"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Joseph Sebastian"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
